name: topobathysim
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pdal
  - python-pdal
  - gdal
  - rasterio
  - xarray
  - rioxarray
  - numpy
  - scipy
  - laspy
  - lazrs-python
  - h5py
  - pystac-client
  - pystac-client
  - planetary-computer
  - s3fs
  - requests
  - bmi-topography=0.9.0
  - rich
  - pyproj
  - joblib
  - uvicorn
  - fastapi
  - python-dotenv
  # Dev dependencies
  - pytest
  - pre-commit
  - ruff
  - mypy
  - pandas-stubs
  - types-PyYAML
  - ipykernel
